// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"Assignment/pkg/api"
	"Assignment/pkg/api/handler"
	"Assignment/pkg/config"
	"Assignment/pkg/db"
	"Assignment/pkg/repository"
	"Assignment/pkg/usecase"
)

// Injectors from wire.go:

func InitializeAPI(cfg config.Config) (*http.ServerHttp, error) {
	gormDB, err := db.ConnectDB(cfg)
	if err != nil {
		return nil, err
	}
	adminRepo := repository.NewAdminRepository(gormDB)
	adminUsecase := usecase.NewAdminUsecase(adminRepo)
	adminaHandler := handler.NewAdminHandler(adminUsecase)
	serverHttp := http.NewServerHttp(adminaHandler)
	return serverHttp, nil
}
